### ISSUE TITLE
lpPositionId  question  :  "msg": "Invalid LP position id"

### ISSUE THREAD

**Issue by WuWhite** [dydxprotocol/v3-client#130]
![image](https://user-images.githubusercontent.com/23696601/136651408-619f13fb-e30a-4454-bf9b-9cd4300aa7e1.png)

    const withdrawal_result = await web3Client_test.private.createFastWithdrawal(
        {
            lpStarkKey: test_account_info.account.starkKey,
            creditAsset: 'USDC',
            creditAmount: '60',
            debitAmount: '100',
            toAddress: walletAddress,
            lpPositionId: '1',
            expiration:  new Date(new Date().getTime() + 60 * 60 * 1000 * 24 * 8),
            clientId,
        },
        test_account_info.account.positionId,
    )

it Always reminding me of 'Invalid LP position id',  when i wanna createFastWithdrawal 
Does anyone have a similar problem?

**Comment by DenisAl-Hazo** [comment]
I have another problem with this method, seems like it doesnt work
```
TypeError: Cannot read property 'replace' of undefined
    at stripHexPrefix (/Users/denis/Desktop/dydx/node_modules/@dydxprotocol/starkex-lib/build/src/lib/util.js:109:29)
    at Object.hexToBn (/Users/denis/Desktop/dydx/node_modules/@dydxprotocol/starkex-lib/build/src/lib/util.js:66:32)
    at SignableConditionalTransfer.calculateHash (/Users/denis/Desktop/dydx/node_modules/@dydxprotocol/starkex-lib/build/src/signable/conditional-transfer.js:42:44)
    at SignableConditionalTransfer.getHashBN (/Users/denis/Desktop/dydx/node_modules/@dydxprotocol/starkex-lib/build/src/signable/stark-signable.js:29:39)
    at SignableConditionalTransfer.sign (/Users/denis/Desktop/dydx/node_modules/@dydxprotocol/starkex-lib/build/src/signable/stark-signable.js:37:35)
    at Private.createFastWithdrawal (/Users/denis/Desktop/dydx/node_modules/@dydxprotocol/v3-client/build/src/modules/private.js:361:56)
   
```

**Comment by sirroger5000** [comment]
Realized that lpPositionId needs to be always 2 ... Don't ask me why.

Got stuck, however with "Invalid signature for fast withdrawal" by calling fast withdrawal

Any idea on that?
